### ISSUE TITLE
Support for Custom User

### ISSUE THREAD

**Issue by pastorhudson** [vsemionov/django-blacklist#1]
When I try to run the migration I get:
```
blacklist.Rule.user: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
```
My settings.AUTH_USER_MODEL:
`AUTH_USER_MODEL = 'users.CustomUser'  # Custom User Model

line 15 in blacklist/models.py needs updated to:
`    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.CASCADE)`

And `from django.conf import settings` needs added to imports.

I can do a PR if you prefer.

**Comment by thatNapoleonDude** [comment]
I have the same problem right now.

**Comment by thatNapoleonDude** [comment]
Did you found a solution?

**Comment by aliceni** [comment]
I also have the same problem.
I hope it can be solved soon.

**Comment by rishabh404-ai** [comment]
Same problem

**Comment by vsemionov** [comment]
Thanks for reporting, and apologies for the huge delay as I was unaware of the activity.
The fix is merged in master and will hopefully be released in a new version soon.
Feel free to reopen if necessary.
