### ISSUE TITLE
Disabling Logging

### ISSUE THREAD

**Issue by sweldon** [vsemionov/django-blacklist#5]
Hello, thanks for your work on the plugin! Would it be possible to add in a setting variable to disable logging? When blacklisted IPs hit our endpoints repeatedly it leads to some spam in our logs. It would be great if we could just reject ip's silently. Thanks very much,
Steve

**Comment by sweldon** [comment]
I have a PR ready to go for this, if you would like to allow me to push a branch

**Comment by sweldon** [comment]
Made a PR for this https://github.com/vsemionov/django-blacklist/pull/6

**Comment by vsemionov** [comment]
Thank you, @sweldon . I've merged the PR and the change will be released with the next version.
