### ISSUE TITLE
Adding proxy

### ISSUE THREAD

**Issue by pinq-** [vsemionov/django-blacklist#8]
Hi,

Can you describe with more detail, how to I pass the proxy server and add clients ip, not proxy ip?

**Comment by vsemionov** [comment]
Hi there,

I wrote a more elaborate description in the readme section called `Proxies and Client Addresses`. I hope this helps. A very thorough and in-depth guide is out of the scope of this documentation. If you need more implementation details, perhaps you can find them at [django-ipware](https://github.com/un33k/django-ipware).
