### ISSUE TITLE
Adding setting that allows to override the header name that contains the real IP address

### ISSUE THREAD

**Issue by jimmybutton** [vsemionov/django-blacklist#9]
Hi there,

thanks a lot for this plugin! It has helped me a lot recently to reduce spam on my blog.

I'm hosting my app on Pythonanywhere. The issue is that they're changing the header of the requests slightly, so the real IP address of the client ends up under a different key, i.e. `request.META.get('HTTP_X_REAL_IP')`, see their [docs](https://help.pythonanywhere.com/pages/WebAppClientIPAddresses/).

I was thinking about adding a setting, e.g. `BLACKLIST_REMOTE_ADDR`, that would allow you to override the default header name (defaults to `"REMOTE_ADDR"`). Would you be happy to review a PR? Many thanks!

**Comment by vsemionov** [comment]
Hi @jimmybutton ,

I'm glad this helps you. Thank you for the suggestion, I think it's a very good idea. I've implemented it in version 0.7.0, so I will close this issue. If you upgrade to the new version, be sure to check the changelog, as the new setting has a different name, and there may be additional steps to upgrade.

Apart from upgrading, another solution would be to write a custom middleware, ordered before django-blacklist. In that middleware, replace REMOTE_ADDR with HTTP_X_REAL_IP.

Cheers!
